name: release
description: "release"
inputs:
  archs:
    description: "archs"
    required: true
  tag:
    description: "tag"
    required: true
  extraTags:
    description: "extra tag"
    required: false
runs:
  using: composite
  steps:
    - name: Populate workspace with source only
      shell: bash
      run: |
        shopt -s dotglob && tmp="$(mktemp -d)" && \
          mv pipelines ${{ inputs.tag }}/* ${tmp}/ && \
          mv .github ${tmp}/ && \
          rm -rf ./* && mv ${tmp}/* . && \
          echo ".github/" >> .melangeignore && tree -a . && \
          sudo rm -rf /work && sudo mkdir /work

    # - name: Setup QEMU
    #   uses: docker/setup-qemu-action@v3
    #   with:
    #     platforms: ${{ inputs.archs }}

    - uses: chainguard-dev/actions/melange-build@main
      with:
        archs: ${{ inputs.archs }}
        multi-config: keycloak-melange.yaml,keycloak-metrics-spi-melange.yaml
        signing-key-path: /work/melange.rsa
        repository-path: /work/packages
        empty-workspace: false
        sign-with-temporary-key: true
        pipeline-dir: pipelines

    - name: Create temp copy of /work directory (used in next step)
      shell: bash
      run: |
        rm -rf .apko-automount && cp -r /work .apko-automount

    - name: Set image name
      shell: bash
      id: image
      run: |
        # Start with the main tag
        ALL_TAGS="latest-${{ inputs.tag }}"

        # Append extraTags if provided
        if [ -n "${{ inputs.extraTags }}" ]; then
          ALL_TAGS="${ALL_TAGS},${{ inputs.extraTags }}"
        fi

        REPO="ghcr.io/${{ github.repository }}"
        IMAGE_TAGS=""

        IFS=',' read -ra TAG_ARRAY <<< "$ALL_TAGS"
        for tag in "${TAG_ARRAY[@]}"; do
          tag=$(echo "$tag" | xargs)  # Trim whitespace
          IMAGE_TAGS="${IMAGE_TAGS} ${REPO}:${tag}"
        done

        IMAGE_TAGS=$(echo "$IMAGE_TAGS" | xargs)  # Trim leading/trailing whitespace
        echo "IMAGE=${IMAGE_TAGS}" >> $GITHUB_OUTPUT

    - uses: chainguard-images/actions/apko-publish@main
      with:
        archs: ${{ inputs.archs }}
        config: apko.yaml
        tag: ${{ steps.image.outputs.IMAGE }}
        keyring-append: /work/melange.rsa.pub
        automount-src: .apko-automount/.
        automount-dest: /work

    - name: Smoke test
      shell: bash
      run: |
        set -e

        # Use the first tag for smoke testing
        refs="${{ steps.image.outputs.IMAGE }}"
        ref=$(echo "$refs" | awk '{print $1}')

        docker pull "${ref}"

        docker run -d --rm -p 9000:9000 \
          -e KEYCLOAK_DATABASE_VENDOR=dev-file \
          -e KEYCLOAK_ENABLE_HEALTH_ENDPOINTS=true \
          -e KC_BOOTSTRAP_ADMIN_PASSWORD=pwd \
          -e KC_CACHE=ispn -e KC_CACHE_CONFIG_FILE=cache-ispn.xml \
          -e KC_HTTP_MANAGEMENT_RELATIVE_PATH=/ \
          --name smoketest "${ref}"

        trap "docker rm -f smoketest" EXIT
        sleep 30 # Give server a few seconds to come up

        curl -v --max-time 10 --fail http://localhost:9000/health
