package:
  name: keycloak-metrics-spi-bitnami
  version: 6.0.0
  epoch: 0
  description: "Adds a Metrics Endpoint to Keycloak"
  copyright:
    - paths:
        - "*"
      attestation: ""
      license: Apache-2.0

environment:
  contents:
    repositories:
      - https://packages.wolfi.dev/os
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    packages:
      - busybox
      - maven
      - openjdk-21
      - openjdk-21-default-jvm
  environment:
    LANG: en_US.UTF-8
    JAVA_HOME: /usr/lib/jvm/java-21-openjdk

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/aerogear/keycloak-metrics-spi
      tag: ${{package.version}}
      expected-commit: bb47bf3e2d9720e02de871db70ecc0dd8fe00530

  - runs: |
      # Build the tool
      mvn clean package versions:set -DnewVersion=${{package.version}} -DskipTests

      mkdir -p ${{targets.destdir}}/opt/bitnami/keycloak/providers

      cp -rf target/keycloak-metrics-spi-*.jar ${{targets.destdir}}/opt/bitnami/keycloak/providers
