# Ref: https://github.com/wolfi-dev/os/blob/main/pipelines/bitnami/compat.yaml
name: Build Bitnami Compatibility Package

needs:
  packages:
    - git

inputs:
  image:
    description: |
      The bitnami image.
    required: true

  tag:
    description: |
      The bitnami/containers tag for the specific version of the image.
    required: true

  expected-commit:
    description: |
      The commit for the tag.
    required: true

  version-path:
    description: |
      The path to the root of the Dockerfile, relative to the image name.
    required: true

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/eminaktas/containers
      tag: ${{inputs.tag}}
      expected-commit: ${{inputs.expected-commit}}
      destination: bitnami
  - runs: |
      mkdir -p ${{targets.contextdir}}
      mkdir -p "${{targets.contextdir}}"/opt/bitnami
      mkdir -p "${{targets.contextdir}}"/bitnami/${{inputs.image}}

      if [ -d "./bitnami/bitnami/${{inputs.image}}/${{inputs.version-path}}/prebuildfs" ]; then
        cp -rf ./bitnami/bitnami/${{inputs.image}}/${{inputs.version-path}}/prebuildfs/* ${{targets.contextdir}}/
      fi

      if [ -d "./bitnami/bitnami/${{inputs.image}}/${{inputs.version-path}}/rootfs" ]; then
        cp -rf ./bitnami/bitnami/${{inputs.image}}/${{inputs.version-path}}/rootfs/* ${{targets.contextdir}}/
      fi

      chmod g+rwX ${{targets.subpkgdir}}/opt/bitnami
