name: presubmit
on:
  pull_request:
    paths:
      - .github/actions/tag-presubmit/action.yml
      - .github/workflows/tag-presubmit.yml
      - pipelines/bitnami/compat.yaml
      - 22/keycloak-melange.yaml
      - 22/keycloak-metrics-spi-melange.yaml
      - 22/apko.yaml
jobs:
  build:
    name: Verify image
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/tag-presubmit
        with:
          archs: amd64 #,arm64
          tag: 22
