name: tag-build
on:
  push:
    tags: [ '*.*.*' ]
jobs:
  build:
    name: Release image with tag
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/tag-release
        with:
          aarchs: amd64 #,arm64
