name: tag-build
on:
  push:
    tags: [ '*.*.*' ]
jobs:
  build:
    name: Release image with tag
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      # - name: Set tag name
      #   id: vars
      #   run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      - uses: ./.github/actions/tag-release
        with:
          archs: x86_64 # ,aarch64 disabled due to failing.
